name: Cobol Check Automation

on: 
  push:
    branches: [ main ]

jobs: 
  cobol-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Set up latest Oracle JDK 24'
      uses: oracle-actions/setup-java@v1
      with:
        website: oracle.com
        release: 24
    # - name: Set up Java
    #   uses: actions/setup-java@v4
    #   with: 
    #     distribution: 'oracle'
    #     java-version: '23'
    - name: Install Zowe CLI
      run: npm install -g @zowe/cli
    - name: Debug Zowe Execution
      run: zowe --version
    - name: Run COBOL Check
      env:
        ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        ZOWE_HOST: ${{ secrets.ZOWE_HOST}}
      run: |
        chmod +x .github/scripts/zowe_operations.sh
        bash .github/scripts/zowe_operations.sh
