---
name: COBOL Check Automation
on:
  push:
    branches: [ main ]
jobs:
  cobol-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Install Zowe CLI
      run: |
        npm install -g @zowe/cli
        zowe --version
    - name: Run COBOL Check on Mainframe
      env:
        ZOWE_OPT_REJECT_UNAUTHORIZED: false
        HOST: ${{ secrets.ZOWE_HOST }}
        USER: ${{ secrets.ZOWE_USERNAME }}
        PSW: ${{ secrets.ZOWE_PASSWORD }}
        PORT: ${{ secrets.ZOWE_PORT }}
      run: |
        chmod +x .github/scripts/zowe_operations.sh
        .github/scripts/zowe_operations.sh
        chmod +x .github/scripts/mainframe_operations.sh
        # command below was changed from the original yaml file
        sshpass -p "$PSW" ssh -o StrictHostKeyChecking=no "$USER"@"$HOST" 'sh -s' < .github/scripts/mainframe_operations.sh
...