---
name: COBOL Check Automation
on:
  push:
    branches: [ main ]
jobs:
  cobol-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Install Zowe CLI
      run: npm install -g @zowe/cli
    - name: Create ZOWE Config
      env:
        ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        ZOWE_HOST: ${{ secrets.ZOWE_HOST }}
        ZOWE_PORT: ${{ secrets.ZOWE_PORT }}
      run: |
        cat <<EOF > zowe.config.json
        {
          "profiles": {
              "zosmf": {
                  "type": "zosmf",
                  "properties": {
                      "port": 10443
                  },
                  "secure": [
                      "user",
                      "password"
                  ]
              },
              "tso": {
                  "type": "tso",
                  "properties": {
                      "account": "FB3",
                      "codePage": "1047",
                      "logonProcedure": "IZUFPROC"
                  },
                  "secure": []
              },
              "ssh": {
                  "type": "ssh",
                  "properties": {
                      "port": 22
                  },
                  "secure": [
                      "user",
                      "password"
                  ]
              },
              "global_base": {
                  "type": "base",
                  "properties": {
                      "host": "",
                      "rejectUnauthorized": false
                  },
                  "secure": [
                      "user",
                      "password"
                  ]
              },
              "zosmfZXPlore": {
                  "type": "zosmf",
                  "properties": {
                      "port": 10443,
                      "host": "204.90.115.200",
                      "rejectUnauthorized": false
                  },
                  "secure": [
                      "user",
                      "password"
                  ]
              },
              "tsoZXPlore": {
                  "type": "tso",
                  "properties": {
                      "account": "FB3",
                      "codePage": "1047",
                      "logonProcedure": "IZUFPROC"
                  },
                  "secure": []
              }
          },
          "defaults": {
              "zosmf": "zosmf",
              "tso": "tso",
              "ssh": "ssh",
              "rse": "rse",
              "base": "global_base"
          },
          "autoStore": true
        }  
        EOF
    - name: Run Zowe Check
      run: |
        zowe --version
        zowe zos-files list data-set "$ZOWE_USERNAME.course.cbl" --host $ZOWE_HOST
    # - name: Run COBOL Check
    #   run: |
    #     chmod +x .github/scripts/zowe_operations.sh
    #     bash .github/scripts/zowe_operations.sh
...